
project_id = "agtjuxiysmzhmpnbuzmc"
[functions.import-vehicle-data]
verify_jwt = true

[functions.amazon-product-search]
verify_jwt = true

[functions.send-sms]
verify_jwt = true

[functions.send-email]
verify_jwt = true

[functions.send-auth-email]
verify_jwt = true

[functions.handle-database-backup]
verify_jwt = true
